name: Sample Workflow

on:
  push:
    branches:
      - main
#on:
#  workflow_call:
#    inputs:
#      aws_region:
#        required: true
#        type: string
#      inputs:
#        aws_role_arn:
#          required: true
#          type: string

jobs:
  github_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} # githubコンテキストをJSON文字列でダンプ

